<?xml version="1.0"?>
<package format="3">
  <name>door_node</name>
  <version>0.0.1</version>
  <description>ROS 2 node that publishes door handle state and provides a toggle service</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
