<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bin_picking_launch</name>
  <version>0.0.0</version>
  <description>Launch files for bin picking robot system</description>
  <maintainer email="user@example.com">Bin Picking Robot Team</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>launch</depend>
  <depend>launch_ros</depend>

  <exec_depend>barcode_node</exec_depend>
  <exec_depend>cell_controller</exec_depend>
  <exec_depend>door_node</exec_depend>
  <exec_depend>emergency_node</exec_depend>
  <exec_depend>stacklight_node</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
