<?xml version="1.0"?>
<package format="3">
  <name>barcode_node</name>
  <version>0.0.1</version>
  <description>ROS 2 node that publishes random barcodes and provides a service to retrieve the latest</description>
  <maintainer email="vigmaha.vignesh3@gmail.com">Vigneshu</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
