<?xml version="1.0"?>
<package format="3">
  <name>cell_controller</name>
  <version>0.0.1</version>
  <description>Cell controller: HTTP API handler + ROS 2 bridge for bin picking cell</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
