<?xml version="1.0"?>
<package format="3">
  <name>stacklight_node</name>
  <version>0.0.1</version>
  <description>ROS 2 node that derives and publishes stack-light state from door and e-button</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
